import React from 'react';
import './global.css';
import { Container } from '@mui/material';
import Alert from '../components/Alert';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Container maxWidth="lg" disableGutters>
          {children}
        </Container>
        <Alert />
      </body>
    </html>
  );
}
